In [190]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
accuracy_dict = {}

In [191]:
dataset = pd.read_csv('breast_cancer.csv')
dataset.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [192]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [193]:
def dictIncrement1D( _dict, key, value ):
    if key in _dict:
        _dict[key] += value
    else:
        _dict[key] = value

## Splitting of data into training and testing set

In [194]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Logistic Regression on Training set

In [195]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Test set result prediction

In [196]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [197]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logistic_regression_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'logistic_regression_accuracy ', logistic_regression_accuracy)

[[84  3]
 [ 3 47]]


## Accuracy with K-fold cross Validation

In [198]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.70 %
Standard Deviation: 1.97 %


## Training the KNN model on Training set

In [199]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Test set result prediction

In [200]:
y_pred = classifier.predict(X_test)
y_pred

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2], dtype=int64)

## Confusion matrix and accuracy score

In [201]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'knn_accuracy', knn_accuracy)

[[84  3]
 [ 1 49]]


## Accuracy with K-fold cross Validation

In [202]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 97.44 %
Standard Deviation: 1.85 %


## Training the SVM model on Training set

In [203]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Test set result prediction

In [204]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [205]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'svm_accuracy ', svm_accuracy)

[[83  4]
 [ 2 48]]


## Accuracy with K-fold cross Validation

In [206]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 97.07 %
Standard Deviation: 2.19 %


## Training Kernal SVM model on Training data

In [207]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Test set result prediction

In [208]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [209]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
kernal_svm_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'kernal_svm_accuracy ', kernal_svm_accuracy)

[[83  4]
 [ 1 49]]


## Accuracy with K-fold cross Validation

In [210]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.89 %
Standard Deviation: 2.17 %


## Training the Naive Bayes model on Training set

In [211]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Test set result prediction

In [212]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [213]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive_bayes_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'naive_bayes_accuracy ', naive_bayes_accuracy)

[[80  7]
 [ 0 50]]


## Accuracy with K-fold cross Validation

In [214]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.52 %
Standard Deviation: 2.24 %


## Training the Decision Tree model on Training set

In [215]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Test set result prediction

In [216]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [217]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
decision_tree_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'decision_tree_accuracy ', decision_tree_accuracy)

[[84  3]
 [ 3 47]]


## Accuracy with K-fold cross Validation

In [218]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 94.33 %
Standard Deviation: 2.65 %


## Training Random Forest model on Training data

In [219]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Test set result prediction

In [220]:
y_pred = classifier.predict(X_test)

## Confusion matrix and accuracy score

In [221]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
random_forest_accuracy = accuracy_score(y_test, y_pred)
dictIncrement1D(accuracy_dict,'random_forest_accuracy ', random_forest_accuracy)

[[83  4]
 [ 3 47]]


## Accuracy with K-fold cross Validation

In [222]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.33 %
Standard Deviation: 2.01 %


## To check best model from accuracy

In [223]:
accuracy_dict

{'logistic_regression_accuracy ': 0.9562043795620438,
 'knn_accuracy': 0.9708029197080292,
 'svm_accuracy ': 0.9562043795620438,
 'kernal_svm_accuracy ': 0.9635036496350365,
 'naive_bayes_accuracy ': 0.948905109489051,
 'decision_tree_accuracy ': 0.9562043795620438,
 'random_forest_accuracy ': 0.948905109489051}

In [224]:
accuracy_series = pd.Series(accuracy_dict)
accuracy_series.sort_values(ascending = False)

knn_accuracy                     0.970803
kernal_svm_accuracy              0.963504
decision_tree_accuracy           0.956204
svm_accuracy                     0.956204
logistic_regression_accuracy     0.956204
random_forest_accuracy           0.948905
naive_bayes_accuracy             0.948905
dtype: float64

## From the above accuracies KNN Classification model is the best model for prediction.